Minor fix to error handling of PlugPlaceholders
Because generator expressions do *not* leak their loop variable into the surrounding scope, the error message did not have the intended behavior. You would see

> InvalidPlugError: Plug <function plug at 0x102a776e0> is a placeholder

Because of the function plug defined earlier in this file.

--

Interestingly, list comprehensions *do* leak their loop variable into the surrounding scope in Python 2 but not Python 3.