Don't complain about uninitialized plugs in StationServer logs (#991)
StationServer seems to be trying to represent (as base type) phase sequences that don't yet have their plugs initialized. This causes a warning to be logged like
```
WARNING:root:Object <class 'my.custom.htf.Plug'> is not initialized, got error _asdict() missing 1 required positional argument: 'self'
```
But has no other effect.

The call stack when that warning is reached is
```
convert_to_base_types (data.py:176)
<dictcomp> (data.py:199)
convert_to_base_types (data.py:201)
<listcomp> (data.py:204)
convert_to_base_types (data.py:206)
<dictcomp> (data.py:199)
convert_to_base_types (data.py:201)
<listcomp> (station_server.py:364)
get (station_server.py:364)
_execute (web.py:1702)
_run (events.py:145)
_run_once (base_events.py:1451)
run_forever (base_events.py:438)
start (asyncio.py:199)
run (web_gui_server.py:157)
run (station_server.py:626)
_bootstrap_inner (threading.py:916)
_bootstrap (threading.py:884)
```

This PR removes that warning, behaviour remains the same.